//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LovePets_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int ID { get; set; }
        public string InGeneral { get; set; }
        public string Nutrition { get; set; }
        public string Care { get; set; }
        public string Health { get; set; }
        public string PhotoLink1 { get; set; }
        public string PhotoLink2 { get; set; }
        public string PhotoLink3 { get; set; }
        public Nullable<int> CategoriesID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
