//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LovePets_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ID { get; set; }
        public System.DateTime RemindingDate { get; set; }
        public string Reminding { get; set; }
        public string ReminderType { get; set; }
        public Nullable<int> ProfileID { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
