//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LovePets_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ID { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Subject { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsRecursive { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> BackR { get; set; }
        public Nullable<int> BackG { get; set; }
        public Nullable<int> BackB { get; set; }
        public Nullable<int> FrontR { get; set; }
        public Nullable<int> FrontG { get; set; }
        public Nullable<int> FrontB { get; set; }
    }
}
